### ISSUE TITLE
We are working on similar think

### ISSUE THREAD

**Issue by GamerClassN7** [shirshak55/smart-home#1]
Hi,
**[me](https://github.com/GamerClassN7)** and **[thebradleysanders](https://github.com/thebradleysanders)** (author of **[IOTSmartHome](https://github.com/thebradleysanders/IOTSmartHome)**) joined the forces and start development of new platform ([Simple-Home](https://github.com/Simple-Home/Simple-Home)) since we both are sharing similar ideas, i From nowhere saw your project **smart-home**, whitch look awesome :) but same like **[IOTSmartHome](https://github.com/thebradleysanders/IOTSmartHome)** is no longer Actively developed. So i started wondering is you will be interested like **[thebradleysanders](https://github.com/thebradleysanders)** and joined you skill , patience, knowledge, etc.  with ours on similar project :) which is actively worked on :) your contribution would be appreciated :) in any quantity :)

Thank you, for your time!
Best Regards
JonatanRek

**Comment by shirshak55** [comment]
Thanks.

In what way can I contribute let me know. You can find my email in github profile

**Comment by GamerClassN7** [comment]
Hello, 
first, really appreciate that you answered !!! Big Thank you :)
could you Join My Discord Server so ve can discuss stuff?  :) I will appreciate any help I can get maybe you could write a module for using open weather API :) Or maybe MQTT Module, Or maybe you can figure some improvements, etc :)

Thank you For your Answer I will be happily waiting in discord server :)
[Simple-Home Discord Server](https://discord.gg/SPRtnBc66v)

**Comment by shirshak55** [comment]
sure thanks.
